// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypzdjqkqwbxeolfrbodk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwemRqcWtxd2J4ZW9sZnJib2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTQzNTQsImV4cCI6MjA2Mzg5MDM1NH0.8k-VQ5NkW2y5nNiKxt1D_HHalFqHUt_pNf4AzCi_BmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);